# Base de datos de ejercicios por grupo muscular

EXERCISES_DB = {
    "Tríceps": [
        "Extension De Triceps C/ Barra En Polea",
        "Extension De Triceps C/ Soga En Polea",
        "Triceps Soga 1 Brazo",
        "Triceps Prono 1 Brazo",
        "Curl De Triceps (Triceps Tras Nuca)",
        "Triceps Tras Nuca 1 Brazo",
        "Patada De Burro C/ Mancuerna",
        "Patada De Burro C/ Mancuerna 1 Brazo",
        "Patada De Burro C/ Mancuerna Alterno",
        "Fondos De Triceps En Cajon",
        "Triceps Supino En Polea",
        "Triceps Supino En Polea 1 Brazo",
        "Triceps Soga Sobre Cabeza (Extension Overhead)",
        "Triceps Soga Sobre Cabeza 1 Brazo",
        "Triceps Sobre Cabeza Toma Prona",
        "Triceps Sobre Cabeza 1 Brazo C/ Toma Prona",
        "Triceps Tras Nuca Polea Baja",
        "Triceps Tras Nuca Polea Baja 1 Brazo",
        "Fondos Pies En Altura",
        "Fondos Con Peso",
        "Patada De Burro En Polea",
        "Press Frances C/ Barra Prono",
        "Press Frances C/ Barra Toma Neutra",
        "Press Frances C/ Mancuerna 1 Brazo",
        "Press Frances C/ Mancuerna",
        "Press Frances En Polea Toma Prono",
        "Press Frances En Polea Toma Neutra",
        "Press Frances En Polea 1 Brazo",
        "Press Frances Trx",
        "Fondos En Paralelas",
        "Fondos En Trx",
        "Press En Banco Plano Supino",
        "Press En Banco Plano Supino 1 Brazo",
        "Press En Banco Supino Alterno",
        "Press En Banco Supino C/ Isotension",
    ],
    "Bíceps": [
        "Curl Alterno C/ Mancuerna",
        "Curl Supino C/ Mancuerna",
        "Curl C/ Barra",
        "Curl Martillo Alterno",
        "Curl Martillo C/ Mancuerna",
        "Curl Martillo C/ Barra",
        "Curl Copa",
        "Curl Supino En Polea",
        "Curl Supino En Polea 1 Brazo",
        "Curl Banco Inclinado C/ Mancuerna (Codo Atras)",
        "Curl Banco Inclinado C/ Mancuerna (Codos Atras)",
        "Curl Banco Inclinado C/ Mancuerna (Codos Al Costado)",
        "Curl Martillo En Polea",
        "Curl Martillo 1 Brazo En Polea",
        "Curl Martillo Cruzado C/ Mancuerna",
        "Curl Martillo Cruzado En Polea",
        "Curl Alterno C/ Isotension",
        "Curl Martillo C/ Isotension",
        "Curl Predicador C/ Mancuerna",
        "Curl Predicador En Polea",
        "Curl Concentrado",
        "Curl 21",
        "Curl Zurman",
        "Curl Basayan",
        "Biceps En Dominada",
    ],
    "Espalda": [
        "Tiron Al Frente Abierto",
        "Remo Prono Polea Alta De Pie",
        "Remo Prono Polea Alta Sentado",
        "Remo Prono Polea Baja",
        "Remo Prono Polea Baja De Pie",
        "Remo Horizontal Toma Prono",
        "Remo Suspendido En Smith Toma Prono",
        "Remo Suspendido En Smith Toma Prono Pies Elevados",
        "Remo Suspendido En Smith Toma Prono C/ Peso",
        "Remo Suspendido Trx Toma Prono",
        "Dominadas Excentricas C/ Banda",
        "Dominadas C/ Banda",
        "Dominadas Completa",
        "Dominadas C/ Peso",
        "Tiron Al Frente Supino",
        "Remo Supino Polea Alta De Pie",
        "Remo Supino Polea Alta Sentado",
        "Remo Supino Polea Baja Sentado",
        "Remo Supino Polea Baja De Pie",
        "Remo Horizontal Toma Supina C/ Mancuerna",
        "Remo Horizontal Toma Supina C/ Barra",
        "Remo Suspendido En Smith Toma Supina",
        "Remo Suspendido En Smith Toma Supina Pies Elevados",
        "Remo Suspendido En Smith Toma Supino C/ Peso",
        "Remo Suspendido Trx Toma Supina",
        "Dominadas Supino Asistidas",
        "Dominadas Supinas C/ Banda",
        "Dominadas Excentricas Supinas",
        "Tiron Al Frente Toma Neutra",
        "Remo Polea Alta Toma Neutra Sentado",
        "Remo Polea Alta Toma Neutra De Pie",
        "Remo Polea Baja Toma Neutra",
        "Remo Polea Baja Toma Neutra De Pie",
        "Remo Horizontal Toma Neutra",
        "Remo Horizontal Toma Neutra C/ Rusa O C/ Mancuerna",
        "Remo Horizontal Toma Neutra Alterno",
        "Remo Suspendido Trx Toma Neutra",
        "Remo En Maquina",
        "Tiron Al Frente Cerrado",
        "Remo Polea Alta Cerrado",
        "Remo Cerrado Polea Baja",
        "Tiron Al Frente 1 Brazo",
        "Remo Polea Alta 1 Brazo Sentado",
        "Remo Polea Alta 1 Brazo",
        "Remo Polea Baja 1 Brazo",
        "Remo Polea Baja 1 Brazo Tipo Estocada",
        "Remo Serrucho C/ Mancuerna Toma Neutra",
        "Remo Serrucho En Polea Toma Neutra",
        "Remo Desde Plancha",
        "Remo Serrucho C/ Mancuerna Supino",
        "Remo Serrucho Polea Baja Supino",
        "Remo Serrucho Toma Prono",
        "Remo Serrucho Toma Prono En Polea",
        "Remo Landmine",
        "Pullover En Banco Plano",
        "Pullover En Polea",
        "Pullover 1 Brazo",
        "Espinales Simples",
        "Espinales Alternos",
        "Espinales C/ Rotacion",
        "Espinales Bird Dog",
        "Espinales Superman",
        "Espinales Superman Isometrico",
        "Espinales Nado",
        "Espinales En Banco",
        "Espinales Parabrisa",
        "Espinales Isometricos",
    ],
    "Hombros": [
        "Press C/ Banda Elastica",
        "Press Militar C/ Barra Sentado",
        "Press Militar C/ Mancuerna Sentado",
        "Press Militar C/ Mancuerna Sentado Alterno",
        "Press Militar C/ Mancuerna Sentado C/ Isotension",
        "Press Militar C/ Mancuerna De Pie",
        "Press Militar C/ Mancuerna Alterno De Pie",
        "Press Militar C/ Mancuerna C/ Isotension",
        "Press Militar C/ Barra De Pie",
        "Press Arnold C/ Mancuerna Sentado",
        "Press Arnold 1 Brazo Sentado",
        "Press Arnold Alterno Sentado",
        "Press Arnold Alterno Sentado C/ Isotension",
        "Press Arnold De Rodillas",
        "Press Arnold De Rodillas Alterno",
        "Press Arnold De Rodillas Alterno C/ Isotension",
        "Press Arnold De Rodillas 1 Brazo",
        "Press Arnold Polea Baja 1 Brazo",
        "Press Arnold De Pie",
        "Press Arnold Alterno",
        "Press Arnold 1 Brazo",
        "Press Arnold 1 Brazo C/ Isometria",
        "Vuelos Frontales C/ Banda",
        "Vuelos Frontales Alterno C/ Mancuerna Sentado",
        "Vuelos Frontales Alterno C/ Mancuerna",
        "Vuelos Frontales En Polea",
        "Vuelos Frontales C/ Mancuerna 2 Brazos",
        "Vuelos Frontales C/ Mancuerna 2 Brazos Sentado",
        "Vuelos Frontales Alterno Sentado C/ Isotension",
        "Vuelos Frontales Alterno C/ Isotension",
        "Vuelos Frontales 1 Brazo En Polea",
        "Vuelos Frontales Toma Neutra Alterno",
        "Vuelos Frontales Toma Neutra 2 Brazos",
        "Vuelos Frontales Toma Neutra En Polea",
        "Vuelos Laterales C/ Banda",
        "Vuelos Laterales C/ Mancuerna Sentado",
        "Vuelos Laterales C/ Mancuerna De Pie",
        "Vuelos Laterales C/ Mancuerna 1 Brazo",
        "Vuelos Laterales 1 Brazo En Polea",
        "Vuelos Laterales Rebote",
        "Vuelos Posteriores C/ Banda Elastica",
        "Vuelos Posteriores C/ Mancuerna Sentado",
        "Vuelos Posteriores C/ Mancuerna De Pie",
        "Vuelos Posteriores En Polea Baja",
        "Encogimiento C/ Barra",
        "Encogimiento C/ Mancuerna",
        "Encogimiento En Polea",
        "Encogimiento En Polea 1 Brazo",
        "Encogimiento C/ Isometria",
        "Remo A Menton C/ Barra",
        "Remo A Menton En Polea",
        "Tiron A Cara C/ Soga",
        "Tiron A Cara Posicion Estocada",
        "Tiron A Cara Polea Baja",
        "Cruces En Polea",
        "Cruces En Polea 1 Brazo",
        "Cruces Banco Inclinado",
        "Halo Con Disco O Rusa",
    ],
    "Pecho": [
        "Press En El Suelo C/ Mancuerna",
        "Press C/ Banda Elastica",
        "Press Plano C/ Barra",
        "Press Plano Alterno C/ Mancuerna",
        "Press Inclinado Alterno C/ Mancuerna",
        "Press Inclinado C/ Barra",
        "Press Plano 1 Brazo",
        "Press Inclinado 1 Brazo",
        "Press Plano C/ Mancuerna",
        "Press Inclinado C/ Mancuerna",
        "Press Alterno En Polea",
        "Press En Polea De Pie",
        "Press En Polea 1 Brazo De Pie",
        "Press Plano En Polea 1 Brazo",
        "Press Inclinado En Polea 1 Brazo",
        "Press Plano En Smith",
        "Press Inclinado En Smith",
        "Press Declinado C/ Mancuerna Alterno",
        "Press Declinado C/ Mancuerna",
        "Press Declinado C/ Barra",
        "Press Declinado 1 Brazo",
        "Aperturas C/ Mancuerna En El Suelo",
        "Aperturas C/ Banda Elastica",
        "Aperturas C/ Mancuerna En Banco Plano",
        "Aperturas C/ Mancuerna En Banco Inclinado",
        "Aperturas C/ Mancuerna En Banco Declinado",
        "Aperturas C/ Mancuerna 1 Brazo En Polea",
        "Cross Over Alterno En Polea",
        "Cross Over En Polea",
        "Cross Over 1 Brazo",
        "Cross Over Ergido Alterno",
        "Cross Over Ergido",
        "Cross Over Ascendente 1 Brazo",
        "Cross Over Ascendente En Polea Banco Inclinado",
        "Cross Over Ascendente C/ Mancuerna En Banco Inclinado",
        "Cross Over Ascendente C/ Mancuerna De Pie",
        "Cross Over Ascendente Alterno C/ Mancuerna",
        "Flexiones",
        "Flexiones C/ Rodillas",
        "Flexiones Inclinadas",
        "Flexiones Sobre Steep",
        "Flexiones Profundas",
        "Flexiones C/ Peso",
        "Flexiones Diamante",
        "Flexiones Diamante C/ Peso",
        "Flexiones Declinadas",
        "Flexiones Con Desplazamiento",
        "Flexiones Spiderman",
        "Flexiones 1 Brazo",
        "Fondos En Cajon",
        "Fondos Pies Elevados",
        "Fondos C/ Peso",
        "Fondos En Paralelas",
        "Press Supino C/ Mancuerna",
        "Press Supino En Polea Baja De Pie",
        "Press Supino En Polea Baja Acostado",
        "Press Supino C/ Mancuerna Alterno",
    ],
    "Cuádriceps": [
        "Sentadillas Trx",
        "Sentadillas Sobre Fitball",
        "Sentadillas Goblet",
        "Sentadillas Goblet Talones Elevados",
        "Sentadillas Landmine",
        "Sentadillas En Smith",
        "Sentadillas Isometricas",
        "Sentadillas Barra Libre",
        "Sentadilla Adelante",
        "Sentadillas Bulgaras C/ Mancuerna",
        "Sentadillas Bulgaras C/ Barra",
        "Sentadillas C/ Salto",
        "Sentadillas Calambre",
        "Sentadillas Jeferson",
        "Sentadillas Pistol Trx",
        "Sentadillas Pistol C/ Apoyo",
        "Sentadillas Pistol",
        "Sentadillas Sumo",
        "Sentadillas Sumo C/ Mancuerna",
        "Sentadillas Sumo Landmine",
        "Sentadillas Sumo C/ Barra",
        "Subidas Al Banco Lateral C/ Mancuerna",
        "Subidas Al Banco Frontal Alterno C/ Mancuerna",
        "Subidas Al Banco Frontal C/ Barra 1 Pierna",
        "Subidas Al Banco Frontal C/ Barra Alterno",
        "Subidas Al Banco Lateral C/ Barra",
        "Subidas Al Banco Cangrejo",
        "Estocadas Estaticas C/ Mancuerna",
        "Estocadas En El Lugar C/ Mancuerna",
        "Estocadas Andando C/ Mancuerna",
        "Estocadas En Smith",
        "Estocadas Estaticas C/ Barra",
        "Estocadas En El Lugar C/ Barra",
        "Estocadas Andando C/ Barra",
        "Estocadas Profundas C/ Mancuerna",
        "Estocadas Profundas C/ Barra",
        "Estocadas Reloj",
        "Estocadas C/ Impulso C/ Mancuerna",
        "Estocadas C/ Salto",
        "Extension De Cuadriceps En Maquina",
        "Extension De Cuadriceps 1 Pierna",
        "Extension De Cuadriceps Isometrico",
        "Saltos Al Cajon",
        "Saltos En Vallas",
        "Saltos Lado A Lado",
        "Aductores En El Suelo",
        "Aductores En Polea",
        "Aductores En Maquina",
        "Flexion De Cadera En Polea",
        "Flexion De Cadera En Polea Acostado",
    ],
    "Isquiotibiales": [
        "Peso Muerto Rumano C/ Barra",
        "Peso Muerto Rumano C/ Mancuerna",
        "Peso Muerto Rumano En Polea",
        "Peso Muerto Rumano Landmine",
        "Peso Muerto Rumano En Smith",
        "Peso Muerto Rumano Pies Asimetricos",
        "Peso Muerto Rumano Bulgaro C/ Mancuerna",
        "Peso Muerto Rumano Bulgaro C/ Barra",
        "Peso Muerto Rumano 1 Pierna C/ Mancuerna",
        "Peso Muerto Rumano 1 Pierna C/ 2 Mancuernas",
        "Peso Muerto Rumano 1 Pierna C/ Barra",
        "Peso Muerto Rumano 1 Pierna En Polea",
        "Peso Muerto Sumo",
        "Puente De Gluteos En El Suelo",
        "Puente De Gluteos Isometrico",
        "Puente De Gluteos En Steep",
        "Puente De Gluteos En Cajon",
        "Puente De Gluteos En Fitball",
        "Puente De Gluteos En Trx",
        "Puente De Gluteos En El Suelo 1 Pierna",
        "Puente De Gluteos En Steep 1 Pierna",
        "Puente De Gluteos 1 Pierna En Cajon",
        "Puente De Gluteos 1 Pierna C/ Banda",
        "Elevacion De Cadera C/ Barra",
        "Elevacion De Cadera C/ Banda En Cadera",
        "Elevacion De Cadera C/ Banda En Rodillas",
        "Elevacion De Cadera Rebote",
        "Elevacion De Cadera Pies Asimetricos",
        "Elevacion De Cadera 1 Pierna",
        "Elevacion De Cadera 1 Pierna C/ Banda",
        "Elevacion De Cadera Isometrico",
        "Flexion Isquiotibial De Pie En Polea",
        "Flexion Isquiotibial 1 Pierna En Polea Acostado",
        "Flexion Isquiotibial En Polea 2 Piernas",
        "Flexion Isquiotibial En Maquina",
        "Flexion Isquiotibial C/ Mancuerna",
        "Flexion Isquiotibial En Maquina 1 Pierna",
        "Flexion Isquiotibial C/ Banda Elastica",
        "Buenos Dias C/ Barra",
        "Buenos Dias En Smith",
        "Sentadillas Sumo Inclinada C/ Mancuerna",
        "Sentadillas Sumo Inclinada Landmine",
        "Estocada Estatica Inclinada",
        "Estocadas Atras Inclinadas",
        "Estocadas Atras Profundas",
        "Estocadas Atras Andando",
        "Estocadas Laterales C/ Mancuerna Abajo",
    ],
    "Glúteos": [
        "Patada De Gluteos En El Suelo C/ Tobillera",
        "Patada De Gluteos C/ Tobillera Pierna Extendida",
        "Patada De Gluteos C/ Tobillera Manteniendo Flexion",
        "Patada De Gluteos C/ Tobillera Rebote",
        "Patada De Gluteos C/ Banda Elastica",
        "Patada De Gluteos En Polea",
        "Patada De Gluteos En Maquina",
        "Patada De Gluteos Pierna Extendida",
        "Patada De Gluteos Rebote En Polea",
        "Patada De Gluteos En Maquina De Remo",
        "Patada De Gluteos Cuadrupedia En Maquina",
        "Patada De Gluteos Cuadripedia En Polea",
        "Patada Cuadripedia En Polea Pierna Extendida",
        "Patada De Gluteos En Smith",
        "Patada De Rana En Smith",
        "Patada De Gluteos En El Suelo Cruzada",
        "Patada De Gluteos En Polea A 45",
        "Patada De Gluteos Cruzada",
        "Patada De Gluteos En Polea Acostado",
        "Patada Cruzada En Polea Cuadrupedia",
        "Elevacion De Cadera C/ Barra",
        "Elevacion De Cadera C/ Banda En Cadera",
        "Elevacion De Cadera C/ Banda En Rodillas",
        "Elevacion De Cadera Rebote",
        "Elevacion De Cadera Pies Asimetricos",
        "Elevacion De Cadera 1 Pierna",
        "Elevacion De Cadera 1 Pierna C/ Banda",
        "Puente De Gluteos En El Suelo",
        "Puente De Gluteos Isometrico",
        "Puente De Gluteos En Steep",
        "Puente De Gluteos En Cajon",
        "Puente De Gluteos En Fitball",
        "Puente De Gluteos En Trx",
        "Puente De Gluteos En El Suelo 1 Pierna",
        "Puente De Gluteos 1 Pierna En Cajon",
        "Puente De Gluteos 1 Pierna C/ Banda",
        "Abertura De Cadera C/ Banda",
        "Abertura De Cadera De Cubito Lateral",
        "Extension De Cadera En Polea De Pie",
        "Extension De Cadera En Altura",
        "Extension De Cadera De Rodillas",
        "Extension De Cadera C/ Banda Elastica",
        "Descenso De Cajon Sostenido",
        "Descenso De Cajon C/ Polea",
        "Descenso De Cajon C/ Mancuerna",
        "Descenso De Cajon C/ Barra",
        "Subidas Al Banco Lateral C/ Mancuerna",
        "Subidas Al Banco Lateral C/ Barra",
        "Estocada Estatica Inclinada",
        "Estocadas Atras Inclinada C/ Mancuerna",
        "Estocadas Atras Profundas",
        "Estocadas Atras Andando",
        "Estocadas Laterales C/ Mancuerna",
        "Estocadas Laterales C/ Barra",
        "Estocada Cruzada Atras C/ Mancuerna",
        "Estocada Cruzada Atras C/ Barra",
        "Estocada Cruzada Atras En Smith",
        "Estocada Lateral C/ Mancuerna",
        "Estocada Lateral C/ Barra",
        "Abductores En El Suelo De Cubito Lateral",
        "Abductores En El Suelo De Cubito Ventral",
        "Abductores En Maquina",
        "Abductores En Polea",
        "Abductores En Polea Acostado De Cubito Lateral",
        "Sentadillas C/ Barra Profundas",
        "Sentadillas Bulgaras Inclinada",
        "Sentadillas Sumo Inclinada",
        "Sentadillas Sumo Landmine",
    ],
    "Gemelos": [
        "Gemelos En Prensa",
        "Gemelos De Pie En Maquina",
        "Gemelos Sentado En Maquina",
        "Gemelos C/ Mancuerna Un Pie",
        "Gemelos 1 Pierna C/ Rusa",
        "Gemelos En Smith",
        "Gemelos De Pie C/ Barra",
        "Elevaciones De Talones De Pie",
        "Elevaciones De Talones Sentado",
        "Tibiales En Polea",
    ],
    "Abdominales": [
        "Abdominales En Maquina",
        "Abdominales Largos C/ Disco",
        "Abdominales Inferiores",
        "Plancha Frontal",
        "Plancha Frontal C/ Antebrazo",
        "Plancha Lateral C/ Antebrazo",
        "Twist C/ Disco",
        "Oblicuos Cruzados",
        "Espinales En Maquina",
        "Espinales Superman",
        "Crunch En Polea Alta",
        "Crunch En Maquina",
        "Elevacion De Piernas Colgado",
        "Rueda Abdominal",
        "Mountain Climbers",
        "Dead Bug",
        "Bird Dog",
    ],
    "Movilidad / Calentamiento": [
        "Movilidad General",
        "Movilidad De Cadera",
        "Movilidad De Hombros",
        "Movilidad De Columna",
        "Estiramiento De Cuadriceps",
        "Estiramiento De Isquiotibiales",
        "Estiramiento De Pectorales",
        "Bici Fija",
        "Caminadora",
        "Eliptica",
        "Saltar La Soga",
        "Remo En Maquina (Cardio)",
    ],
}


def get_all_exercises():
    result = []
    for grupo, ejercicios in EXERCISES_DB.items():
        for nombre in ejercicios:
            result.append({"grupo": grupo, "nombre": nombre})
    return result
